#!/usr/bin/python3
"""
Password Generator Module
"""
###############################################################################

__author__ = "Jared Winter"
__copyright__ = "Copyright 2019, jwinternet"
__credits__ = ""
__license__ = "GNU GPL v3"
__version__ = "v0.0.7"
__updated__ = "10/22/2019"
__email__ = "jaredwinter2015@outlook.com"
__contributors__ = ""
__status__ = "PROD"

###############################################################################

import random
import string

###############################################################################

# Pool of characters that are drawn upon to create a password
chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$"
chars_vowels = "aeiou"
chars_lower = "abcdefghijklmnopqrstuvwxyz"
chars_upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
chars_number = "0123456789"
chars_symbol = "@!#$%^+=?"

def password_generator():
	"""
	Creates a new password using random characters.
	"""
	play = 0
	print("\nBelow are 10 randomly generated passwords:")
	while play < 10:
		new_password = random.choice(chars_vowels)
		new_password += random.choice(chars_vowels)
		new_password += random.choice(chars_upper)
		new_password += random.choice(chars_vowels)
		new_password += random.choice(chars_number)
		new_password += random.choice(chars_vowels)
		new_password += random.choice(chars_symbol)
		new_password += random.choice(chars_vowels)
		password_list = list(new_password)
		random.SystemRandom().shuffle(password_list)
		new_password = ''.join(password_list)
		print("\n" + new_password)
		play += 1

###############################################################################

if __name__ == "__main__":
    main()
